### ISSUE TITLE
Where to submit feedback, typos, corrections, etc.?

### ISSUE THREAD

**Issue by rldotai** [rltheorybook/rltheorybook.github.io#1]
This book recently got my attention-- it's a very necessary project since RL theory knowledge is currently so dispersed across a number of books and papers.
However, your website asks for feedback, but there doesn't appear to be a recommended place to submit said feedback.

Could you determine how interested readers should provide feedback, and then update the website/pdf accordingly?

**Comment by shamulent** [comment]
Hi Brendan. Could you please email me at sham at cs . washington . edu for any suggestions? I missed this message!
